### ISSUE TITLE
Boundary is not considered properly

### ISSUE THREAD

**Issue by YANLING-H** [EdwardHaoranLee/WoodokuLearn#34]
boundary is not considered properly in Woodkuboard.can_add_shape_to_board. Instead of searching all locations on the board, one should only search for locations that could possibly fit the given shape.

**Comment by Xiaorui-Huang** [comment]
require a meeting to discuss changing how WoodukuShape is read from file

**Comment by Xiaorui-Huang** [comment]
Where I describe the problem

https://github.com/EdwardHaoranLee/WoodokuLearn/pull/26#discussion_r928278662
https://github.com/EdwardHaoranLee/WoodokuLearn/pull/26#discussion_r928279263

**Comment by Xiaorui-Huang** [comment]
my proposed solution is to add a boundary field to shapes. 
this keeps track of the border of a shape so that problems in #34 do not happen

If we were to keep the rotate function, then these values should be determined at 2 places the `__init__()` of shape and predetermined at `rotate()` that the border around the coordinate is tight.

I mean the broader is tight by

This is tight:
|  	| ■ 	|
|---	|:---:	|
| ■ 	| ■ 	|
|  	| ■ 	|

This is not tight: 

|  	|  	| ■ 	|
|---	|:---:	|---	|
|  	| ■ 	| ■ 	|
|  	|  	| ■ 	|

I'd need some input for suggestions.
@EdwardHaoranLee @YANLING-H

**Comment by EdwardHaoranLee** [comment]
I am against the idea to add a boundary field. It will bring a greater difficulty to our code base especially when we are adding a shape to the board. The original intention of `rotate()` is to also handle the "shift" after rotating.

Though it might increase the implementation complexity of `rotate()`, it is still a doable approach.

**Comment by Xiaorui-Huang** [comment]
put rotate aside, how are we handling boundaries? as per the main topic of this issue and highlighted in https://github.com/EdwardHaoranLee/WoodokuLearn/pull/26#discussion_r928279263
Cause I doubt recomputing the boundary of a shape is a nice solution either
